FROM golang:1.22 AS build
WORKDIR /src
COPY . .
RUN go build -o /out/ingest-api ./cmd/ingest-api
FROM gcr.io/distroless/base-debian12
COPY --from=build /out/ingest-api /ingest-api
ENTRYPOINT ["/ingest-api"]
